name: easy_comic
description: "Easy Comic - 您的专属漫画阅读器"
publish_to: 'none'

version: 1.0.0+1000

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  # Flutter
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4

  # Data Persistence & Database
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.4
  path: ^1.8.3
  shared_preferences: ^2.5.3

  # Functional Programming & Utilities
  dartz: ^0.10.1
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  intl: ^0.19.0
  
  # Networking
  webdav_client: ^1.2.2
  connectivity_plus: ^6.0.5
  
  # File & Image Handling
  file_picker: ^10.2.0
  archive: ^4.0.7
  image_picker: ^1.1.2
  image_cropper: ^9.1.0

  # UI & UX
  dynamic_color: ^1.7.0
  wakelock_plus: ^1.2.1
  home_widget: ^0.3.0

dev_dependencies:
  # Build & Code Generation
  build_runner: ^2.4.9
  drift_dev: ^2.18.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # Testing
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

  # Linting & Code Style
  flutter_lints: ^6.0.0

  # App Icons
  flutter_launcher_icons: ^0.14.4
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"