name: easy_comic
description: "Easy Comic - 您的专属漫画阅读器"
publish_to: 'none'

version: 1.0.0+1000

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  archive: ^4.0.7
  async: ^2.13.0
  crypto: ^3.0.3
  drift: ^2.18.0
  dynamic_color: ^1.7.0
  file_picker: ^10.2.0
  firebase_analytics: ^10.10.7
  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.5.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  home_widget: ^0.8.0
  palette_generator: ^0.3.3+3
  path: ^1.8.3
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.0
  webdav_client: ^1.2.2
  workmanager: ^0.8.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.18.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_annotation: ^4.8.1
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"