name: Build and Release to Google Play

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Decode Google Service Account JSON
      id: service_account_json
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: service-account.json
        encodedString: ${{ secrets.PLAY_STORE_JSON_KEY_BASE64 }}
        
    - name: Flutter Pub Get
      working-directory: ./Easy-Comic
      run: flutter pub get

    - name: Build App Bundle
      working-directory: ./Easy-Comic
      run: flutter build appbundle --release

    - name: Setup Ruby and Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Fastlane
      run: gem install fastlane

    - name: Upload to Play Store (Internal)
      working-directory: ./Easy-Comic
      run: |
        fastlane run upload_to_play_store \
          track:internal \
          aab:build/app/outputs/bundle/release/app-release.aab \
          json_key:../service-account.json